### ISSUE TITLE
 Capitalization of STD names

### ISSUE THREAD

**Issue by edean1** [codeforkansascity/I-Got-Mine#104]
The names are stored somewhere in javascript.  If you switch from Spanish to English and back to English the names are pulled from google spreadsheet.  The capitalization in the spreadsheet is correct. We need to fix capitalization of names which are stored in javascript (the original).  
Also, the treatment title in symptoms cards is rendered as "view pictures from past events" after switching from English to Spanish and back to English.  
Also, the names of diseases (trichamoniasis and public lice) (which are stored in javascript) should be shortened to trich and crabs

**Comment by tangospring** [comment]
Edited the names. The names are stored in Google Spreadsheet in STD Testing tab.
