### ISSUE TITLE
Localization reference bug

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/I-Got-Mine#105]
The treatment title in symptoms cards is rendered as "view pictures from past events" after switching from English to Spanish and back to English.

**Comment by johnkary** [comment]
I think this is caused by the l10n.js JavaScript code not properly accounting for rows that do not have an "lkey" in Row 1.

To fix this issue:
1. I removed all blank columns in the spreadsheet.
2. Ensured every column had a text key in Row 1.

**Comment by tangospring** [comment]
done
