### ISSUE TITLE
Mobile layout only: make STD Treatment Center cards collapsible

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/I-Got-Mine#107]
**\* All of this is for narrow (mobile) screens only. Current desktop layout is good. ***

Collapsed card shows blue Treatment Center icon to the left of the title (hide the icon when the card is expanded) . 
Under the title is address.
Under the address wide orange bar spanning the width of the card: "Show more info".

The expanded card looks like it is now with addition of the action  bar under the address with the label: "Hide info".

**Comment by sqyttles** [comment]
I'll look into it this weekend.

**Comment by tangospring** [comment]
done. Thanks John.
