### ISSUE TITLE
Change title of PrEP

### ISSUE THREAD

**Issue by zmon** [codeforkansascity/I-Got-Mine#127]
Expanding the graphic title of PrEP to “Is PrEP Right for You?”; this title also needs to be on the main display ribbon

- [X] Created Workaround
- [ ] Need to change css for H2 so it does not capitalize, should show as "PrEP" - need to figure out how to compile sass

**Comment by troland65** [comment]
added html tag to not put upper case on the title and typed the title as desired with mixed cases
