### ISSUE TITLE
Add link view to map with icon

### ISSUE THREAD

**Issue by edean1** [codeforkansascity/I-Got-Mine#38]
Add link "View on map" in the events and std treatment sections

**Comment by tangospring** [comment]
Make images for "standout" icons. For example, when treatment centers link is selected, the map icons for treatment centers should be highlighted. 

--- the icons are done -- look for map icons with suffix "-selected"

**Comment by tangospring** [comment]
Write script for highlighting the icons. Also would be nice to have a set of tabs on top of the map:  [All] [<icon> Condoms (23)] [<icon> Events (8)] [<icon> Treatment (4)]. The tabs will serve as a map legend as well.

**Comment by flyakite** [comment]
Added simple buttons in cefbef3fd5f57116f09f3a6ea95fafc589ceb8ef
Any button with a class 'highlight-marker' and a 'data-type' will work.

**Comment by tangospring** [comment]
done
