### ISSUE TITLE
Add mouse scroll wheel zoom to the map

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/I-Got-Mine#73]

**Comment by flyakite** [comment]
I'm not sure if a scroll action triggers a zoom on the map is the best practice in a single page application. Are there any websites doing this?

**Comment by tangospring** [comment]
A usability issue similar to finger-scrolling on mobile maps? 
Well, we could add the map wheel scroll zoom to the desktop popup (if the functional map popup will be displayed on desktop -- there is no real need to modify map on desktops, only on finger driven devices).
