### ISSUE TITLE
Events in the carousel display date two times. Hide Google 'Date' field data.

### ISSUE THREAD

**Issue by tangospring** [codeforkansascity/I-Got-Mine#90]
Both Date and Days fields are pulled into Events carousel. We need to hide 'Date' field from spreadsheet at the website.

Related: Events in the map "event info'  popup display the date two times. == this one is fixed (duplicate in the spreadsheet) - OK.

**Comment by tangospring** [comment]
This can be fixed by edits in Google spreadsheet.

**Comment by vikeen** [comment]
I made a pull request for this issue. https://github.com/codeforkansascity/I-Got-Mine/pull/97

**Comment by tangospring** [comment]
Fixed. Thanks vikeen.

**Comment by vikeen** [comment]
You're welcome. I've got another PR coming for the #72 - map icon tooltips
